# Generated by Django 4.1.5 on 2023-03-12 20:22

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('buyticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
