# Generated by Django 4.1.5 on 2023-03-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyticket', '0005_ticketprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(default='all', max_length=40),
        ),
    ]
