# Generated by Django 4.1.5 on 2023-03-16 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyticket', '0006_payment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='type',
            new_name='tictype',
        ),
    ]
